### ISSUE TITLE
How to obtain 'n_eff'

### ISSUE THREAD

**Issue by hoangthienan95** [ajaynadig/bhr#13]
Hi there,

I'm trying to run my own BHR analysis using sum stats from genebass. However, I got stuck on this line: https://github.com/ajaynadig/bhr/blob/40b4a8a2f0315548910dd0fd3d7287f69432bbb6/example/genebass_variant_filter_january_2023.py#L25-L27

The Supplementary Table column key define `n_eff` as "Effective sample size from Genebass analysis for continuous traits" but I can't find where the `n_eff` column is in the Genebass data (gs://ukbb-exome-public/500k/results/variant_results.mt). Supplementary table 5 of the paper has `n_eff` for only 37 traits.

Where can I find `n_eff`? Thanks!

**Comment by ajaynadig** [comment]
Hello,
Estimates of N_effective (computed with SAIGE) for all genebass traits can be found in this public HailTable:

`gs://ukbb-exome-public/500k/qc/n_eff.ht`

**Comment by hoangthienan95** [comment]
Thanks for the rapid response!!!!

**Comment by ajaynadig** [comment]
No problem, feel free to reopen if you have additional issues
