### ISSUE TITLE
BHR in clearly monogenic disorders

### ISSUE THREAD

**Issue by oalavijeh** [ajaynadig/bhr#16]
Dear Ajay and team, 

Have you tried BHR on known diseases with strong monogenic architecture? I have tried running it on a few renal disorders with a known  monogenic architecture and am getting varying results. I would like to know if you have done any bench-marking with similar traits/diseases? 

All the best

**Comment by ajaynadig** [comment]
Hello,
While we have not run BHR on diseases that are known to be monogenic, we do have some experience with traits that have extremely large effect genes. 

Under the hood, BHR employs a random effects model, and basically estimates a mean true effect size across all genes. If there are large-effect outlier genes, they can strongly influence this mean, and lead to large standard errors. In our original analysis, we noticed that this was the case for serum LDL and LoF mutations in _APOB_. This motivated us to use a mixed model for BHR, where large-effect genes are not included in the random effects model, to avoid this issue. This is why, in the BHR output, there are separate sections for mixed-model (with large effect genes separated out) and subthreshold_genes (random effects model with large effect genes removed) (note also that when there are no large effect genes and no fixed effect genes specified, subthreshold_genes and mixed_model will be identical). To force BHR to model a certain set of genes as fixed, you should use the `fixed_genes` argument.  

So, in summary: if you use the mixed model as described above, setting fixed_genes to the known monogenic cause, BHR should be able to handle monogenic-like traits quite well. If the trait is truly monogenic, then the random effects model will return 0 heritability, and all heritability will all come from the fixed effect. In this case, the `significant_genes` output will give potentially interesting estimates of what proportion of heritability comes from the known monogenic cause. I suspect that very few traits are actually truly monogenic, and BHR could be an interesting way to infer a contribution from other genes (although I do not know much about renal disorders, so am unsure about your particular trait of interest). 

Beyond that, it is difficult to give specific recommendations, as they are likely dependent on the details of your scientific question.

Hope that's helpful!

**Comment by oalavijeh** [comment]
That's very helpful and clear. Many thanks!
