### ISSUE TITLE
Selecting phenotypes for download from genebass

### ISSUE THREAD

**Issue by oalavijeh** [ajaynadig/bhr#7]
Dear BHR team, 

Many thanks for the great tool. I am looking to run BHR on a subset of genebass phenotypes and am not a native python used. Looking at the https://github.com/ajaynadig/bhr/blob/master/example/genebass_variant_filter_january_2023.py#L8 srcipt:

1. If I want to only download summary stats from a single phenotype then do I edit the input file in line 8 of this script? Supplementary table 4 from your nature paper does not look like the right table (I assume it is ST5). In which case do I copy the info from genebass into similar column headings at ST5 (not sure what n_bhr and n_eff is). 

All the best

**Comment by danjweiner** [comment]
Hi,

Thanks for your question!

If you want to download summary statistics for a single phenotype, then starting with the Python script you linked to:
1) Delete lines 7-13
2) Below current line 6, start a new line which is:

```
genebass_variant = genebass_variant.filter_cols(genebass_variant.phenocode == [the phenocode you want])
```

There may be multiple ways to reference the phenotype you want, but phenocode may work. You can look up the phenocode on Genebass. For example, if you wanted to download the statistics for creatinine, the phenocode is 30700 based on the information on this page: https://app.genebass.org/gene/undefined/phenotype/continuous-30700-both_sexes--irnt

Hope this helps, and let us know if any questions,
Dan

**Comment by oalavijeh** [comment]
Dear Dan, 

Many thanks that is super helpful! 

Last question. Is the example scripts to take the genebass data forwards: https://github.com/ajaynadig/bhr/blob/master/example/run_BHR.R ? 

Many thanks

**Comment by danjweiner** [comment]
Hi,

For basic BHR usage with Genebass-downloded summary statistics, please refer to this page on the Wiki:

https://github.com/ajaynadig/bhr/wiki/Example:-Height-&-BMI-(basic)

Hope this helps!
Dan

**Comment by oalavijeh** [comment]
Thanks again!
